-- DAYA Platform
-- Content Module Migration
-- Jalankan setelah migration Authentication, Creator, dan Creator Identity.

CREATE TABLE IF NOT EXISTS contents (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    creator_id BIGINT UNSIGNED NOT NULL,
    content_code VARCHAR(30) NOT NULL,
    content_type VARCHAR(50) NOT NULL,
    title VARCHAR(190) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    excerpt TEXT NOT NULL,
    body LONGTEXT NOT NULL,
    cover_image_url VARCHAR(255) NOT NULL DEFAULT '',
    seo_title VARCHAR(150) NOT NULL DEFAULT '',
    seo_description VARCHAR(255) NOT NULL DEFAULT '',
    access_policy VARCHAR(50) NOT NULL DEFAULT 'free',
    price_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
    currency_code VARCHAR(10) NOT NULL DEFAULT 'IDR',
    visibility VARCHAR(20) NOT NULL DEFAULT 'public',
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    views_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    likes_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    comments_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    shares_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    sponsor_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    donation_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    affiliate_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    revenue_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
    recommendation_score INT UNSIGNED NOT NULL DEFAULT 0,
    published_at DATETIME NULL,
    reviewed_at DATETIME NULL,
    reviewed_by_user_id BIGINT UNSIGNED NULL,
    review_notes TEXT NOT NULL,
    deleted_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_contents_content_code (content_code),
    UNIQUE KEY uq_contents_slug (slug),
    KEY idx_contents_creator_id (creator_id),
    KEY idx_contents_content_type (content_type),
    KEY idx_contents_status (status),
    KEY idx_contents_visibility (visibility),
    KEY idx_contents_deleted_at (deleted_at),
    CONSTRAINT fk_contents_creator FOREIGN KEY (creator_id) REFERENCES creator_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_contents_reviewed_by FOREIGN KEY (reviewed_by_user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS content_parts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(190) NOT NULL,
    summary TEXT NOT NULL,
    body LONGTEXT NOT NULL,
    media_url VARCHAR(255) NOT NULL DEFAULT '',
    is_free_preview TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT UNSIGNED NOT NULL DEFAULT 1,
    release_at DATETIME NULL,
    deleted_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_content_parts_content_id (content_id),
    KEY idx_content_parts_release_at (release_at),
    KEY idx_content_parts_deleted_at (deleted_at),
    CONSTRAINT fk_content_parts_content FOREIGN KEY (content_id) REFERENCES contents (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
