-- STORY MODULE — DAYA Platform Framework v1.0
-- MySQL 8.x, InnoDB, utf8mb4

CREATE TABLE IF NOT EXISTS stories (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    creator_id BIGINT UNSIGNED NOT NULL,
    collection_id BIGINT UNSIGNED NULL,
    story_code VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    subtitle VARCHAR(200) NOT NULL DEFAULT '',
    slug VARCHAR(220) NOT NULL,
    summary TEXT NOT NULL,
    body LONGTEXT NOT NULL,
    cover VARCHAR(255) NOT NULL DEFAULT '',
    language VARCHAR(10) NOT NULL DEFAULT 'id',
    genre VARCHAR(100) NOT NULL DEFAULT '',
    tags VARCHAR(255) NOT NULL DEFAULT '',
    word_count INT UNSIGNED NOT NULL DEFAULT 0,
    reading_time INT UNSIGNED NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    visibility VARCHAR(20) NOT NULL DEFAULT 'private',
    seo_title VARCHAR(150) NOT NULL DEFAULT '',
    seo_description VARCHAR(255) NOT NULL DEFAULT '',
    canonical_url VARCHAR(255) NOT NULL DEFAULT '',
    og_title VARCHAR(150) NOT NULL DEFAULT '',
    og_description VARCHAR(255) NOT NULL DEFAULT '',
    og_image VARCHAR(255) NOT NULL DEFAULT '',
    json_ld_placeholder LONGTEXT NOT NULL,
    published_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_stories_story_code (story_code),
    UNIQUE KEY uq_stories_slug (slug),
    KEY idx_stories_creator_id (creator_id),
    KEY idx_stories_collection_id (collection_id),
    KEY idx_stories_status (status),
    KEY idx_stories_visibility (visibility),
    KEY idx_stories_published_at (published_at),
    KEY idx_stories_deleted_at (deleted_at),
    CONSTRAINT fk_stories_creator_id FOREIGN KEY (creator_id) REFERENCES creator_profiles (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_stories_collection_id FOREIGN KEY (collection_id) REFERENCES collections (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

