<?php

declare(strict_types=1);

return [
    'statuses' => [
        'draft' => 'Draft',
        'pending_review' => 'Pending Review',
        'active' => 'Active',
        'rejected' => 'Rejected',
        'suspended' => 'Suspended',
        'revoked' => 'Revoked',
    ],
    'kyc_statuses' => [
        'unsubmitted' => 'Unsubmitted',
        'pending_review' => 'Pending Review',
        'verified' => 'Verified',
        'rejected' => 'Rejected',
    ],
    'verification_statuses' => [
        'unverified' => 'Unverified',
        'pending_review' => 'Pending Review',
        'verified' => 'Verified',
        'trusted' => 'Trusted',
        'rejected' => 'Rejected',
    ],
    'creator_types' => [
        'individual' => 'Individual',
        'organization' => 'Organization',
        'brand' => 'Brand',
        'community' => 'Community',
    ],
    'creator_levels' => [
        'emerging' => 'Emerging',
        'growing' => 'Growing',
        'established' => 'Established',
        'icon' => 'Icon',
    ],
    'portfolio_types' => [
        'book' => 'Books',
        'story' => 'Stories',
        'audio' => 'Audio',
        'podcast' => 'Podcast',
        'experience' => 'Experience',
        'award' => 'Awards',
        'certificate' => 'Certificates',
    ],
    'badge_catalog' => [
        'verified' => 'Verified Creator',
        'trusted' => 'Trusted Creator',
        'rising_star' => 'Rising Star',
        'top_author' => 'Top Author',
        'top_speaker' => 'Top Speaker',
        'community_builder' => 'Community Builder',
    ],
    'default_category' => 'General',
    'default_creator_type' => 'individual',
    'default_creator_level' => 'emerging',
    'default_verification_status' => 'pending_review',
    'categories' => [
        'General',
        'Education',
        'Business',
        'Technology',
        'Lifestyle',
        'Arts',
        'Faith',
        'Community',
    ],
    'social_platforms' => [
        'website' => 'Website',
        'instagram' => 'Instagram',
        'youtube' => 'YouTube',
        'tiktok' => 'TikTok',
        'x' => 'X / Twitter',
        'linkedin' => 'LinkedIn',
    ],
    'statistic_fields' => [
        'followers_count',
        'reads_count',
        'listens_count',
        'downloads_count',
        'sponsor_count',
        'donation_count',
        'affiliate_count',
        'revenue_minor',
        'wallet_available_minor',
        'wallet_pending_minor',
    ],
    'public_page_enabled_default' => false,
];
